remote_theme: pmarsceill/just-the-docs
search_enabled: false
title: Yeh Chan Yoo
description: Yeh Chan Yoo's professional portfolio website
aux_links:
  "LinkedIn Profile":
    - "https://www.linkedin.com/in/yehchan-yoo/"
  "Resume":
    - "Yeh Chan Yoo's Resume for Portfolio Website.docx.pdf"
  "CV":
    - "Yeh Chan Yoo's Curriculum Vitae.pdf"
